CCC = g++
LEX = flex
YACC = bison
CFLAGS = -Wall
LEXFLAGS = -Wno-unused -Wno-sign-compare

OBJS = main.o parse.tab.o lex.yy.o

run: $(OBJS)
	$(CCC) $(CFLAGS) -o run $(OBJS)

main.o: main.cpp
	$(CCC) $(CFLAGS) -c main.cpp

parse.tab.c: parse.y
	$(YACC) -d parse.y

parse.tab.o: parse.tab.c
	$(CCC) $(CFLAGS) -c parse.tab.c

lex.yy.c: scan.l parse.tab.o
	$(LEX) scan.l

lex.yy.o: lex.yy.c
	$(CCC) $(CFLAGS) $(LEXFLAGS) -c lex.yy.c
	
clean:
	rm -f run *.o parse.tab.c lex.yy.c
	rm -f parse.tab.h
